### PR TITLE
Added soccerama.pro in payed subscription section

### PR DESCRIPTION
**Pull request by RonnieVisser**

### CODE REVIEW

**Comment by RonnieVisser** [comment]
Hope you can add this site.

thanks

**Comment by jokecamp** [comment]
Thanks. I will review and then publish.

**Comment by RonnieVisser** [comment]
thanks!

**Comment by RonnieVisser** [comment]
Any news on the review process? Hope you have time soon!

**Comment by jokecamp** [comment]
The API has been published to the list at jokecamp.com

**Pull request merged**
